[package]
name = "mind2t-vt-render"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
bytemuck = "1.25.2"
pollster = "1.0.1"
mind2t-vt-frame.workspace = true
mind2t-vt-snapshot.workspace = true
swash = "0.2"
thiserror.workspace = true
wgpu = "26.0.1"

[dev-dependencies]
mind2t-vt-core.workspace = true
mind2t-vt-pty.workspace = true
