[package]
name = "ruuah-vt-pty"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dev-dependencies]
ruuah-vt-snapshot.workspace = true

[dependencies]
ruuah-vt-core.workspace = true
ruuah-vt-frame.workspace = true
thiserror.workspace = true
rustix = { version = "1.1", features = ["pty", "termios", "process", "fs", "event"] }
