//! Raw bindings to libghostty-vt, generated by bindgen at build time.
//!
//! Generated rather than hand-written on purpose: this is the oracle, and a silently
//! wrong struct offset here would poison every comparison downstream without ever
//! failing loudly. `abi_guard.rs` cross-checks the result against the library's own
//! `ghostty_type_json()` report, so a header/binary mismatch is caught too.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
