//! Native hardware keycode -> `Key`, one table per platform. GENERATED by
//! `scripts/gen-keymap.ts` from the oracle's keycode table (`src/input/keycodes.zig`, itself
//! Chromium's dom_code_data) and the C key enum order. Regenerate, never hand-edit.
//! 110 macOS entries, 120 Linux entries.
//!
//! Why this exists at all: a host that reads native key events gets a hardware keycode, which
//! is not the W3C code name the encoder is keyed on. Every host needs that translation, and it
//! comes from ONE generator because two hand-kept copies of a 110-entry table drift silently
//! and present as "one key does nothing".
//!
//! Why it is per platform rather than one table: the hardware code for a physical key is not
//! the same number on macOS and on Linux, and nothing can make it be. What IS shared is the
//! row - both columns come from the same Chromium entry, so the two tables cannot disagree
//! about which physical key a DomCode names. That is the whole reason they are generated
//! together instead of in two passes.
//!
//! **The Linux table's identification is a hypothesis and is labelled one.** The xkb column is
//! the X11 keycode (evdev + 8, asserted by the generator over every row). GDK documents
//! `GdkEventKey.hardware_keycode` only as "the raw code of the key that was pressed or
//! released" and says nothing about which convention that is, so the claim that a GTK host can
//! hand this table its `hardware_keycode` directly is unproven until a key is pressed on a real
//! Linux machine. It is written down here rather than discovered as "one key does nothing".

use crate::key::Key;

/// `(macOS virtual keycode, GhosttyKey value)`, sorted by keycode for binary search.
///
/// The second element indexes `Key::ALL` by construction: the C enum's value IS its position
/// in that list, which `keys!` guarantees.
pub const MACOS_KEYCODES: &[(u16, u16)] = &[
    (0, 20), // KeyA
    (1, 38), // KeyS
    (2, 23), // KeyD
    (3, 25), // KeyF
    (4, 27), // KeyH
    (5, 26), // KeyG
    (6, 45), // KeyZ
    (7, 43), // KeyX
    (8, 22), // KeyC
    (9, 41), // KeyV
    (11, 21), // KeyB
    (12, 36), // KeyQ
    (13, 42), // KeyW
    (14, 24), // KeyE
    (15, 37), // KeyR
    (16, 44), // KeyY
    (17, 39), // KeyT
    (18, 7), // Digit1
    (19, 8), // Digit2
    (20, 9), // Digit3
    (21, 10), // Digit4
    (22, 12), // Digit6
    (23, 11), // Digit5
    (24, 16), // Equal
    (25, 15), // Digit9
    (26, 13), // Digit7
    (27, 46), // Minus
    (28, 14), // Digit8
    (29, 6), // Digit0
    (30, 4), // BracketRight
    (31, 34), // KeyO
    (32, 40), // KeyU
    (33, 3), // BracketLeft
    (34, 28), // KeyI
    (35, 35), // KeyP
    (36, 58), // Enter
    (37, 31), // KeyL
    (38, 29), // KeyJ
    (39, 48), // Quote
    (40, 30), // KeyK
    (41, 49), // Semicolon
    (42, 2), // Backslash
    (43, 5), // Comma
    (44, 50), // Slash
    (45, 33), // KeyN
    (46, 32), // KeyM
    (47, 47), // Period
    (48, 64), // Tab
    (49, 63), // Space
    (50, 1), // Backquote
    (51, 53), // Backspace
    (53, 120), // Escape
    (54, 60), // MetaRight
    (55, 59), // MetaLeft
    (56, 61), // ShiftLeft
    (57, 54), // CapsLock
    (58, 51), // AltLeft
    (59, 56), // ControlLeft
    (60, 62), // ShiftRight
    (61, 52), // AltRight
    (62, 57), // ControlRight
    (64, 137), // F17
    (65, 95), // NumpadDecimal
    (67, 104), // NumpadMultiply
    (69, 90), // NumpadAdd
    (71, 79), // NumLock
    (75, 96), // NumpadDivide
    (76, 97), // NumpadEnter
    (78, 107), // NumpadSubtract
    (79, 138), // F18
    (80, 139), // F19
    (81, 98), // NumpadEqual
    (82, 80), // Numpad0
    (83, 81), // Numpad1
    (84, 82), // Numpad2
    (85, 83), // Numpad3
    (86, 84), // Numpad4
    (87, 85), // Numpad5
    (88, 86), // Numpad6
    (89, 87), // Numpad7
    (90, 140), // F20
    (91, 88), // Numpad8
    (92, 89), // Numpad9
    (96, 125), // F5
    (97, 126), // F6
    (98, 127), // F7
    (99, 123), // F3
    (100, 128), // F8
    (101, 129), // F9
    (103, 131), // F11
    (105, 133), // F13
    (106, 136), // F16
    (107, 134), // F14
    (109, 130), // F10
    (110, 55), // ContextMenu
    (111, 132), // F12
    (113, 135), // F15
    (114, 72), // Insert
    (115, 71), // Home
    (116, 74), // PageUp
    (117, 68), // Delete
    (118, 124), // F4
    (119, 69), // End
    (120, 122), // F2
    (121, 73), // PageDown
    (122, 121), // F1
    (123, 76), // ArrowLeft
    (124, 77), // ArrowRight
    (125, 75), // ArrowDown
    (126, 78), // ArrowUp
];

/// The key a macOS virtual keycode denotes, or `Unidentified` for one with no mapping.
pub fn key_from_macos_keycode(code: u16) -> Key {
    lookup(MACOS_KEYCODES, code)
}

/// `(X11/xkb keycode, GhosttyKey value)`, sorted by keycode for binary search.
///
/// This is the evdev scancode plus 8, which is what X11 reports and what GTK is believed to
/// pass through as `hardware_keycode`. See the module card: the belief is not yet measured.
pub const LINUX_KEYCODES: &[(u16, u16)] = &[
    (9, 120), // Escape
    (10, 7), // Digit1
    (11, 8), // Digit2
    (12, 9), // Digit3
    (13, 10), // Digit4
    (14, 11), // Digit5
    (15, 12), // Digit6
    (16, 13), // Digit7
    (17, 14), // Digit8
    (18, 15), // Digit9
    (19, 6), // Digit0
    (20, 46), // Minus
    (21, 16), // Equal
    (22, 53), // Backspace
    (23, 64), // Tab
    (24, 36), // KeyQ
    (25, 42), // KeyW
    (26, 24), // KeyE
    (27, 37), // KeyR
    (28, 39), // KeyT
    (29, 44), // KeyY
    (30, 40), // KeyU
    (31, 28), // KeyI
    (32, 34), // KeyO
    (33, 35), // KeyP
    (34, 3), // BracketLeft
    (35, 4), // BracketRight
    (36, 58), // Enter
    (37, 56), // ControlLeft
    (38, 20), // KeyA
    (39, 38), // KeyS
    (40, 23), // KeyD
    (41, 25), // KeyF
    (42, 26), // KeyG
    (43, 27), // KeyH
    (44, 29), // KeyJ
    (45, 30), // KeyK
    (46, 31), // KeyL
    (47, 49), // Semicolon
    (48, 48), // Quote
    (49, 1), // Backquote
    (50, 61), // ShiftLeft
    (51, 2), // Backslash
    (52, 45), // KeyZ
    (53, 43), // KeyX
    (54, 22), // KeyC
    (55, 41), // KeyV
    (56, 21), // KeyB
    (57, 33), // KeyN
    (58, 32), // KeyM
    (59, 5), // Comma
    (60, 47), // Period
    (61, 50), // Slash
    (62, 62), // ShiftRight
    (63, 104), // NumpadMultiply
    (64, 51), // AltLeft
    (65, 63), // Space
    (66, 54), // CapsLock
    (67, 121), // F1
    (68, 122), // F2
    (69, 123), // F3
    (70, 124), // F4
    (71, 125), // F5
    (72, 126), // F6
    (73, 127), // F7
    (74, 128), // F8
    (75, 129), // F9
    (76, 130), // F10
    (77, 79), // NumLock
    (78, 149), // ScrollLock
    (79, 87), // Numpad7
    (80, 88), // Numpad8
    (81, 89), // Numpad9
    (82, 107), // NumpadSubtract
    (83, 84), // Numpad4
    (84, 85), // Numpad5
    (85, 86), // Numpad6
    (86, 90), // NumpadAdd
    (87, 81), // Numpad1
    (88, 82), // Numpad2
    (89, 83), // Numpad3
    (90, 80), // Numpad0
    (91, 95), // NumpadDecimal
    (95, 131), // F11
    (96, 132), // F12
    (104, 97), // NumpadEnter
    (105, 57), // ControlRight
    (106, 96), // NumpadDivide
    (107, 148), // PrintScreen
    (108, 52), // AltRight
    (110, 71), // Home
    (111, 78), // ArrowUp
    (112, 74), // PageUp
    (113, 76), // ArrowLeft
    (114, 77), // ArrowRight
    (115, 69), // End
    (116, 75), // ArrowDown
    (117, 73), // PageDown
    (118, 72), // Insert
    (119, 68), // Delete
    (125, 98), // NumpadEqual
    (127, 150), // Pause
    (133, 59), // MetaLeft
    (134, 60), // MetaRight
    (135, 55), // ContextMenu
    (141, 173), // Copy
    (143, 175), // Paste
    (145, 174), // Cut
    (191, 133), // F13
    (192, 134), // F14
    (193, 135), // F15
    (194, 136), // F16
    (195, 137), // F17
    (196, 138), // F18
    (197, 139), // F19
    (198, 140), // F20
    (199, 141), // F21
    (200, 142), // F22
    (201, 143), // F23
    (202, 144), // F24
];

/// The key an X11/xkb hardware keycode denotes, or `Unidentified` for one with no mapping.
pub fn key_from_linux_keycode(code: u16) -> Key {
    lookup(LINUX_KEYCODES, code)
}

/// Shared by both tables, so a platform cannot acquire its own lookup rule by accident.
///
/// `Unidentified` rather than a guess: the encoder already treats it as "produces no bytes
/// unless the event carries text", which is the correct behaviour for a key we cannot name.
fn lookup(table: &[(u16, u16)], code: u16) -> Key {
    match table.binary_search_by_key(&code, |(keycode, _)| *keycode) {
        Ok(index) => table
            .get(index)
            .and_then(|(_, value)| Key::ALL.get(usize::from(*value)).copied())
            .unwrap_or(Key::Unidentified),
        Err(_) => Key::Unidentified,
    }
}
