//! macOS virtual keyCode -> `Key`. GENERATED by `scripts/gen-keymap.ts` from the
//! oracle's keycode table (`src/input/keycodes.zig`, itself Chromium's dom_code_data mac
//! column) and the C key enum order. Regenerate, never hand-edit. 110 entries.
//!
//! Why this exists in Rust as well as Swift: a host that reads AppKit key events gets a
//! hardware virtual keycode, which is not the W3C code name the encoder is keyed on. Both
//! hosts need the same translation and it comes from one generator, because two hand-kept
//! copies of a 110-entry table drift silently and present as "one key does nothing".

use crate::key::Key;

/// `(macOS virtual keycode, GhosttyKey value)`, sorted by keycode for binary search.
///
/// The second element indexes `Key::ALL` by construction: the C enum's value IS its position
/// in that list, which `keys!` guarantees.
pub const MACOS_KEYCODES: &[(u16, u16)] = &[
    (0, 20), // KeyA
    (1, 38), // KeyS
    (2, 23), // KeyD
    (3, 25), // KeyF
    (4, 27), // KeyH
    (5, 26), // KeyG
    (6, 45), // KeyZ
    (7, 43), // KeyX
    (8, 22), // KeyC
    (9, 41), // KeyV
    (11, 21), // KeyB
    (12, 36), // KeyQ
    (13, 42), // KeyW
    (14, 24), // KeyE
    (15, 37), // KeyR
    (16, 44), // KeyY
    (17, 39), // KeyT
    (18, 7), // Digit1
    (19, 8), // Digit2
    (20, 9), // Digit3
    (21, 10), // Digit4
    (22, 12), // Digit6
    (23, 11), // Digit5
    (24, 16), // Equal
    (25, 15), // Digit9
    (26, 13), // Digit7
    (27, 46), // Minus
    (28, 14), // Digit8
    (29, 6), // Digit0
    (30, 4), // BracketRight
    (31, 34), // KeyO
    (32, 40), // KeyU
    (33, 3), // BracketLeft
    (34, 28), // KeyI
    (35, 35), // KeyP
    (36, 58), // Enter
    (37, 31), // KeyL
    (38, 29), // KeyJ
    (39, 48), // Quote
    (40, 30), // KeyK
    (41, 49), // Semicolon
    (42, 2), // Backslash
    (43, 5), // Comma
    (44, 50), // Slash
    (45, 33), // KeyN
    (46, 32), // KeyM
    (47, 47), // Period
    (48, 64), // Tab
    (49, 63), // Space
    (50, 1), // Backquote
    (51, 53), // Backspace
    (53, 120), // Escape
    (54, 60), // MetaRight
    (55, 59), // MetaLeft
    (56, 61), // ShiftLeft
    (57, 54), // CapsLock
    (58, 51), // AltLeft
    (59, 56), // ControlLeft
    (60, 62), // ShiftRight
    (61, 52), // AltRight
    (62, 57), // ControlRight
    (64, 137), // F17
    (65, 95), // NumpadDecimal
    (67, 104), // NumpadMultiply
    (69, 90), // NumpadAdd
    (71, 79), // NumLock
    (75, 96), // NumpadDivide
    (76, 97), // NumpadEnter
    (78, 107), // NumpadSubtract
    (79, 138), // F18
    (80, 139), // F19
    (81, 98), // NumpadEqual
    (82, 80), // Numpad0
    (83, 81), // Numpad1
    (84, 82), // Numpad2
    (85, 83), // Numpad3
    (86, 84), // Numpad4
    (87, 85), // Numpad5
    (88, 86), // Numpad6
    (89, 87), // Numpad7
    (90, 140), // F20
    (91, 88), // Numpad8
    (92, 89), // Numpad9
    (96, 125), // F5
    (97, 126), // F6
    (98, 127), // F7
    (99, 123), // F3
    (100, 128), // F8
    (101, 129), // F9
    (103, 131), // F11
    (105, 133), // F13
    (106, 136), // F16
    (107, 134), // F14
    (109, 130), // F10
    (110, 55), // ContextMenu
    (111, 132), // F12
    (113, 135), // F15
    (114, 72), // Insert
    (115, 71), // Home
    (116, 74), // PageUp
    (117, 68), // Delete
    (118, 124), // F4
    (119, 69), // End
    (120, 122), // F2
    (121, 73), // PageDown
    (122, 121), // F1
    (123, 76), // ArrowLeft
    (124, 77), // ArrowRight
    (125, 75), // ArrowDown
    (126, 78), // ArrowUp
];

/// The key a macOS virtual keycode denotes, or `Unidentified` for one with no mapping.
///
/// Unidentified rather than a guess: the encoder already treats it as "produces no bytes unless
/// the event carries text", which is the correct behaviour for a key we cannot name.
pub fn key_from_macos_keycode(code: u16) -> Key {
    match MACOS_KEYCODES.binary_search_by_key(&code, |(keycode, _)| *keycode) {
        Ok(index) => MACOS_KEYCODES
            .get(index)
            .and_then(|(_, value)| Key::ALL.get(usize::from(*value)).copied())
            .unwrap_or(Key::Unidentified),
        Err(_) => Key::Unidentified,
    }
}
